FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir flask==3.1.2

COPY mock_downstream.py .
ENV FLASK_APP=mock_downstream.py
EXPOSE 8001

CMD ["flask", "run", "--host=0.0.0.0", "--port=8001"]